### ISSUE TITLE
[NativeMediaPlayer] [FEATURE REQUEST] Expose MediaEventListener events by getter property 

### ISSUE THREAD

**Issue by Manurocker95** [Glitch9Inc/Glitch9-Support#12]
If you want to use the events (for not implementing them by hand), you need to use the inspector. However, when using obfuscation this will present an issue. Exposing the UnityEvents by accesing them in a getter, allows to reference them. As well as having add an event with the boolean value instead of having true/false ones.

**Comment by Glitch9Inc** [comment]
Please refert to https://github.com/Glitch9Inc/Glitch9-Support/issues/3
