### ISSUE TITLE
[NativeMediaPlayer] [FEATURE REQUEST] Set UnityTester/UnityEditorPlayer for non-mobile devices

### ISSUE THREAD

**Issue by Manurocker95** [Glitch9Inc/Glitch9-Support#13]
Using #if (!UNITY_ANDROID && !UNITY_IOS) || UNITY_EDITOR in that script (and references) allows to compile and use the regular audiosource behaviour on every other platform. Otherwise, the code won't compile when switching platforms even if the plugin is not used.

**Comment by Glitch9Inc** [comment]
please refer to https://github.com/Glitch9Inc/Glitch9-Support/issues/4
