### ISSUE TITLE
[NativeMediaPlayer] [FEATURE REQUEST] Add a window tab to set the iOS permissions

### ISSUE THREAD

**Issue by Manurocker95** [Glitch9Inc/Glitch9-Support#14]
These permissions are really hidden in editor and can be easily skip. Adding a window tab AND updating the documentation to explicit say you require this to make AVAudioSession to work would be nice.

![image](https://github.com/Glitch9Inc/Glitch9-Support/assets/17181899/c99ec26b-4393-4d87-a025-fb2ac248e7a3)

**Comment by Glitch9Inc** [comment]
![image](https://github.com/Glitch9Inc/Glitch9-Support/assets/162673831/d6e6d2b3-7529-4407-96a3-32425bbdee54)
I've added codes to adds those options to the info.plist. 
This will execute on build.
The code used to be there before, but it's somehow gone. So I added them back.
