### ISSUE TITLE
[NativeMediaPlayer] [FEATURE REQUEST] Add a toggle to disable OnDestroyOnLoad

### ISSUE THREAD

**Issue by Manurocker95** [Glitch9Inc/Glitch9-Support#16]
If you have multiple scenes you might not want the NMP to be persistent but be kept in specific scene. Adding a toggle to disable this behaviour would be nice.

**Comment by Glitch9Inc** [comment]
Thank you for your suggestion. Unfortunately, it's not possible to disable NMP persistence due to Unity's lifecycle. If the native plugin sends a message and NMP is not present, it will crash.
