### ISSUE TITLE
[NativeMediaPlayer] [BUG] Changes in com.glitch9.media2.aar crash the application

### ISSUE THREAD

**Issue by Manurocker95** [Glitch9Inc/Glitch9-Support#21]
The 29/6 changes for the AAR located in Assets\Glitch9\NativePlugins\NativeMediaPlayer\Plugins\Android\com.glitch9.media2.aar without the rest of the changes trigger a  Warn System.err [NativeMediaPlayer] Player is null. Please make sure you have called [NativeMediaPlayer.create()] before calling this method.
 
With the rest of the changes, the app directly crash. 

Note that this is with manual initialization and auto init disabled.

**Comment by Manurocker95** [comment]
I see the crash itself is a combination of the aar and MediaItem line 162:  if (MetadataStatus != MetadataStatus.Unset) return; 

The aar keeps it from playing if the mediaitem change is removed. The rest of the changes with previous aar and without the metadatastatus change, plays just fine. Takes more than before to load but it plays.

**Comment by Manurocker95** [comment]
This does not happen in the 1/7 package. However, only when autoInit is set. An error with You can't initialize NativeMediaPlayer manually when AutoInit is enabled is triggered, as well as 7 times HandleInitialization

**Comment by Glitch9Inc** [comment]
Customers and I confirmed that there is no crash with manual initialization. Closing this. (Will reopen if anyone still has crashing issue)
