### ISSUE TITLE
[NativeMediaPlayer] [BUG] playing single item takes 5-10 seconds to load 

### ISSUE THREAD

**Issue by Manurocker95** [Glitch9Inc/Glitch9-Support#22]
Since last version from the store, the player takes about 5-10 seconds to load from persistentDatapath even when the audio is 10 seconds length.

**Comment by Glitch9Inc** [comment]
I can't reproduce this bug. Needs more information.

**Comment by Manurocker95** [comment]
> I can't reproduce this bug. Needs more information.

Try the sample provided to load from persistent datapath on a 4GB or less android device like Redmi Note 9 or below.

**Comment by Manurocker95** [comment]
> I can't reproduce this bug. Needs more information.

To make it simpler to reproduce, use audios in mp3 with 6 min length, located in a folder with other 10 more in persistentDataPath. Use the initialize(platlist)/setPlaylist(playlist) with the item loaded by hand (with manually created metadata referencing a 512x512 sprite as artwork that is loaded from Resouece Load/by inspector) when pressing a UI button. So make an scene with 5 buttons. On press, load different audios.

**Comment by Glitch9Inc** [comment]
Oh so this is the same issue with this one: https://github.com/Glitch9Inc/Glitch9-Support/issues/9
