### ISSUE TITLE
[NativeMediaPlayer] [BUG] Background controls not appearing on iOS

### ISSUE THREAD

**Issue by Manurocker95** [Glitch9Inc/Glitch9-Support#26]
The music is playing with the app being minimized but on iOS 17.4 the seek bar and selected buttons in Preferences (forward, rewind, play/stop) are not appearing on iOS menu. Use Seekbar is toggled and Disable AV AudioSession toggle is untoggled.

**Comment by Glitch9Inc** [comment]
I resolved it by handling AVAudioSession in main thread.
