### ISSUE TITLE
[NativeMediaPlayer] Please expose the events from MediaEventListener

### ISSUE THREAD

**Issue by amaiichigopurin** [Glitch9Inc/Glitch9-Support#3]
Please for next version expose by properties the events from MediaEventListener to access them by code instead of editor. Gonna test the latest version and report.

**Comment by Glitch9Inc** [comment]
You can access the MediaEvents via MediaEvents.cs with codes.

![image](https://github.com/Glitch9Inc/Glitch9-Support/assets/162673831/95b116dc-85ef-4373-a7c0-7d270a9e5f73)

**Comment by Manurocker95** [comment]
> You can access the MediaEvents via MediaEvents.cs with codes.
> 
> ![image](https://private-user-images.githubusercontent.com/162673831/344360021-95b116dc-85ef-4373-a7c0-7d270a9e5f73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDc1ODQsIm5iZiI6MTcxOTY0NzI4NCwicGF0aCI6Ii8xNjI2NzM4MzEvMzQ0MzYwMDIxLTk1YjExNmRjLTg1ZWYtNDM3My1hN2MwLTdkMjcwYTllNWY3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQwNzQ4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTEzZTdmYmZjNjRiMGY3ZGY1OTBiOTY3MDIzYjljODRiYmJiMzVkMTg2NjBlYTdjOTg4YzA1NzExNGE2YjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AS6Lcov9BuZBtCcEm540KXjIpW487lrR71TJ52Sa0Ms)

This would require you to make your own script when you have provided already one.

**Comment by Glitch9Inc** [comment]
![image](https://github.com/Glitch9Inc/Glitch9-Support/assets/162673831/a1562d8f-f476-486a-b9ed-c4cf8a6cb96f)
This is just for the people who wants to use the inspector. You can remove this object and callbacks will still work.
