### ISSUE TITLE
[NativeMediaPlayer] UnityTester compile symbol

### ISSUE THREAD

**Issue by amaiichigopurin** [Glitch9Inc/Glitch9-Support#4]
it would be nice to have the previous UnityTester (now UnityEditorPlayer) as #if !UNITY_ANDROID && !UNITY_IOS, to avoid compilation errors when compiling to different platforms with the asset in the project. As it would work as regular unity audios, it won't affect regular workflow.

**Comment by Glitch9Inc** [comment]
Thanks for the suggestion. 
It already has #if UNITY_EDITOR, which has the same effect.
