### ISSUE TITLE
[NativeMediaPlayer] iOS error in MediaPlayer.cs

### ISSUE THREAD

**Issue by amaiichigopurin** [Glitch9Inc/Glitch9-Support#5]
iOS has a small error:

Assets/Glitch9/NativePlugins/NativeMediaPlayer/Scripts/MediaPlayer/MediaPlayer.cs(277,22): error CS0103: The name 'enabled' does not exist in the current context

**Comment by Glitch9Inc** [comment]
Added fix on 4.2.5.
