### ISSUE TITLE
[NativeMediaPlayer] iOS AVAudioSession error

### ISSUE THREAD

**Issue by amaiichigopurin** [Glitch9Inc/Glitch9-Support#6]
![image](https://github.com/Glitch9Inc/Glitch9-Support/assets/74164090/1037d78f-c3fb-4280-8d23-57e051e91be8)
https://forums.developer.apple.com/forums/thread/714598

**Comment by Glitch9Inc** [comment]
![image](https://github.com/Glitch9Inc/Glitch9-Support/assets/162673831/81e8db1d-29fa-40fe-942c-1417dc6896e1)
On line 191.

**Comment by Glitch9Inc** [comment]
Only happening iOS version from iOS16.

**Comment by Glitch9Inc** [comment]
From my experience, the only option that works with Unity was 'AVAudioSessionCategoryOptionMixWithOthers'. I'm not sure why it changed. I'm chaging it back. Needs testing. 
![image](https://github.com/Glitch9Inc/Glitch9-Support/assets/162673831/f3f43e05-33ba-4ea0-a5e4-cd65c749ee5a)

**Comment by Manurocker95** [comment]
> ![image](https://private-user-images.githubusercontent.com/74164090/344359693-1037d78f-c3fb-4280-8d23-57e051e91be8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDQ2MzIsIm5iZiI6MTcxOTY0NDMzMiwicGF0aCI6Ii83NDE2NDA5MC8zNDQzNTk2OTMtMTAzN2Q3OGYtYzNmYi00MjgwLThkMjMtNTdlMDUxZTkxYmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA2NTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZThmY2Q3OWYwN2JiNTI4MDcxZDBlYTEzYWUwMzgzMzIxOWQ1Njc0ZGZhMGRlNmNkM2E3M2NmYzAzNGEzZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QSLs9uXLkBE-_siq2BXrtLdDtPXs1NS89BCCP3PqxLM) https://forums.developer.apple.com/forums/thread/714598

Seems to be the same error exposed here: https://forums.developer.apple.com/forums/thread/714598

where they recommend to disable the AVAudioSession before changin the category and enable it afterwards. Due to this bug, the rest of the audio play (even from different apps) get stuck until the device is restarted.

**Comment by Glitch9Inc** [comment]
Is this still happening?

**Comment by Manurocker95** [comment]
> Is this still happening?

Not tested yet

**Comment by Glitch9Inc** [comment]
This issue was likely due to the AVAudioSession being set on a non-main thread. Closing.
