### ISSUE TITLE
[NativeMediaPlayer] [Error] Compilation error on iOS

### ISSUE THREAD

**Issue by Manurocker95** [Glitch9Inc/Glitch9-Support#8]
Assets/Glitch9/NativePlugins/NativeMediaPlayer/Scripts/MediaPlayer/MediaPlayer.cs(277,22): error CS0103: The name 'enabled' does not exist in the current context

As it is a setter, I guess it should check the sent "value" but this shows a compilation error.

**Comment by Glitch9Inc** [comment]
https://github.com/Glitch9Inc/Glitch9-Support/issues/5
Fixed (not on store yet)
