### ISSUE TITLE
[NativeMediaPlayer] [BUG] Playlists with +10 items loaded from URL or PersistentDataPath freeze the device for a huge amount of time.

### ISSUE THREAD

**Issue by Manurocker95** [Glitch9Inc/Glitch9-Support#9]
When initializing a very big playlist (+10 items), the asset seems to be loading all the audios and saving them into memory. This freezes the devices. A recommendation would be just loading the audioclip that it's going to play, as well as the Metadata. 

The initialization/setPlaylist should be made async to avoid collapsing the main thread.

**Comment by Glitch9Inc** [comment]
The issue arises because Unity completely halts when running in the background, preventing our native plugin from receiving any data during this time. Also, the initialization and setting of the playlist are already handled asynchronously on the native side.

The practical solution here is to send all items, but process them one by one to avoid overwhelming the system. I'll try to implement it after the crashing and repeat mode issues are resolved.

**Comment by Glitch9Inc** [comment]
PlayerPrefs can only save up to 1mb. This is most likely the issue because currently the entire playlist is saved to one PlayerPrefs key. If each media item has their own key, it will likely to be solved.

However, this is connected to many init logic so will require careful approach and will require a lot of testing.

**Comment by Glitch9Inc** [comment]
Oh nvm I just noticed playlists don't use PlayerPrefs anymore like before. I've just added compression which lowers the string size to 1/4.

**Comment by Manurocker95** [comment]
The app to crash (probably getting out of memory) on Redmi Note 9 with +50 items.

**Comment by Manurocker95** [comment]
Related to this bug:

AndroidJavaException: java.lang.OutOfMemoryError: Failed to allocate a 6741416 byte allocation with 5893496 free bytes and 5755KB until OOM, target footprint 268435456, growth limit 268435456
java.lang.OutOfMemoryError: Failed to allocate a 6741416 byte allocation with 5893496 free bytes and 5755KB until OOM, target footprint 268435456, growth limit 268435456
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loopOnce(Looper.java:210)
android.os.Looper.loop(Looper.java:299)

**Comment by Glitch9Inc** [comment]
Thanks for the error log!

**Comment by Glitch9Inc** [comment]
I've added codes to send data from unity to java by data chunks! It's working on Android. I gotta add the same thing for iOS.

**Comment by Manurocker95** [comment]
> I've added codes to send data from unity to java by data chunks! It's working on Android. I gotta add the same thing for iOS.

The data chunk update completely freezes the device (the unity main thread).

**Comment by Manurocker95** [comment]
Single item freezes temporary and then triggers this:

AndroidJavaException: java.lang.OutOfMemoryError: Failed to allocate a 1392360 byte allocation with 495152 free bytes and 483KB until OOM, target footprint 268435456, growth limit 268435456
java.lang.OutOfMemoryError: Failed to allocate a 1392360 byte allocation with 495152 free bytes and 483KB until OOM, target footprint 268435456, growth limit 268435456
java.util.Arrays.copyOf(Arrays.java:3578)
java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:177)
java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:753)
java.lang.StringBuffer.append(StringBuffer.java:431)
java.io.StringWriter.write(StringWriter.java:77)
com.google.gson.stream.JsonWriter.string(JsonWriter.java:592)
com.google.gson.stream.JsonWriter.value(JsonWriter.java:418)
com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:707)
com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:721)
com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:655)
com.google.gson.internal.Streams.write(Streams.java:72)
com.google.gson.JsonElement.toString(JsonElement.java:316)
com.glitch9.media2.metadata.NativeMediaMetadata.toJson(NativeMediaMetadata.java:102)
com.glitch9.media2.metadata.NativeMediaMetadataJsonWriter.WriteMetadataToJson(NativeMediaMetadataJsonWriter.java:21)
com.glitch9.media2.playlist.Playlist.handleMetadataType(Playlist.java:88)
com.glitch9.media2.playlist.Playlist.<init>(Playlist.java:64)
com.glitch9.media2.Media2.processData(Media2.java:137)
com.glitch9.media2.Media2.$r8$lambda$2ciMAVAim7f76ihqAWdchtbEwgA(Unknown Source:0)
com.glitch9.media2.Media2$$ExternalSyntheticLambda1.accept(Unknown Source:4)
com.glitch9.media2.utils.DataReceiver.receiveDataChunk(DataReceiver.java:40)
com.glitch9.media2.Media2.receiveDataChunk(Media2.java:117)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loopOnce(Looper.java:210)
android.os.Looper.loop(Looper.java:299)
com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._Call (System.IntPtr methodID, System.Object[] args) (at <00000000000000000000000000000000>:0)
Glitch9.NativePlugins.NativeMediaPlayer.MediaPlayer.HandleInitialization (System.Boolean playWhenReady, System.Int32 startMediaItemIndex, System.Single startPosition) (at <00000000000000000000000000000000>:0)
Glitch9.NativePlugins.NativeMediaPlayer.MediaPlayer.Initialize (Glitch9.NativePlugins.NativeMediaPlayer.Playlist playlist, System.Nullable`1[T] playWhenReady, System.Nullable`1[T] startMediaItemIndex, System.Single startPosition) (at <00000000000000000000000000000000>:0)

**Comment by Manurocker95** [comment]
The "freezing" time is hugely reduced on my Retroid Pocket 4, which has better processor than my Redmi Note 9 and 8GB of RAM. This confirms it's something with the backend loading. However, the player still crashes after displaying same error with different memory and allocation:

AndroidJavaException: java.lang.OutOfMemoryError: Failed to allocate a 26895192 byte allocation with 6154936 free bytes and 6010KB until OOM, target footprint 268435456, growth limit 268435456
java.lang.OutOfMemoryError: Failed to allocate a 26895192 byte allocation with 6154936 free bytes and 6010KB until OOM, target footprint 268435456, growth limit 268435456
android.util.Base64.decode(Base64.java:160)
android.util.Base64.decode(Base64.java:138)
android.util.Base64.decode(Base64.java:120)
com.glitch9.media2.utils.Decompressor.decompressString(Decompressor.java:16)
com.glitch9.media2.Media2.processData(Media2.java:131)
com.glitch9.media2.Media2.$r8$lambda$2ciMAVAim7f76ihqAWdchtbEwgA(Unknown Source:0)
com.glitch9.media2.Media2$$ExternalSyntheticLambda1.accept(Unknown Source:4)
com.glitch9.media2.utils.DataReceiver.receiveDataChunk(DataReceiver.java:40)
com.glitch9.media2.Media2.receiveDataChunk(Media2.java:117)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loopOnce(Looper.java:201)
android.os.Looper.loop(Looper.java:288)
com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._Call (System.IntPtr methodID, System.Object[] args) (at <00000000000000000000000000000000>:0)
Glitch9.NativePlugins.NativeMediaPlayer.MediaPlayer.HandleInitialization (System.Boolean playWhenReady, System.Int32 startMediaItemIndex, System.Single startPosition) (at <00000000000000000000000000000000>:0)
Glitch9.NativePlugins.NativeMediaPlayer.MediaPlayer.Initialize (Glitch9.NativePlugins.NativeMediaPlayer.Playlist playlist, System.Nullable`1[T] playWhenReady, System.Nullable`1[T] startMediaItemIndex, System.Single startPosition) (at <00000000000000000000000000000000>:0)

**Comment by Glitch9Inc** [comment]
Now Artworks gets saved to persistentDataPath when serializing a mediaitem and native retrieves the image file from the persistentDataPath.
Test successful with 30 mediaitems with 2mb images. (persistentDataPath)
I also removed 'downloadAndPlay' and combined it to 'persistentDataPath', so you might need to adjust your paths and uriType before   testing this version.
 
https://drive.google.com/file/d/1-t1X3f56BSobClTEoC1MRd-nAd7Hcd-5/view?usp=sharing

**Comment by Manurocker95** [comment]
> Now Artworks gets saved to persistentDataPath when serializing a mediaitem and native retrieves the image file from the persistentDataPath. Test successful with 30 mediaitems with 2mb images. (persistentDataPath) I also removed 'downloadAndPlay' and combined it to 'persistentDataPath', so you might need to adjust your paths and uriType before   testing this version.  
Still crashing:

![image](https://github.com/Glitch9Inc/Glitch9-Support/assets/17181899/740310a0-54a9-4e0c-b30d-531d79341d24)

**Comment by Glitch9Inc** [comment]
I added the missing String null check shown in your error log.
Try replacing the aar with the one in the attachment.
It means the path is empty.

------------------------------------------------------------------------------

For bug reports or issues, please visit  Glitch9-Support Issues (https://github.com/Glitch9Inc/Glitch9-Support/issues).

Work Hours:
Korea Standard Time (KST):

Monday to Friday: 9:30 AM - 8:00 PM

Saturday: Closed

Sunday: 12:00 PM - 6:00 PM

Pacific Standard Time (PST):

Monday to Friday: 4:30 PM (previous day) - 3:00 AM

Saturday: Closed

Sunday: 7:00 PM (previous day) - 1:00 AM

 
On 2024-07-05 17:51, Manuel Rodríguez Matesanz  ***@***.***>  wrote:
> >
> > Now Artworks gets saved to persistentDataPath when serializing a mediaitem and native retrieves the image file from the persistentDataPath. Test successful with 30 mediaitems with 2mb images. (persistentDataPath) I also removed 'downloadAndPlay' and combined it to 'persistentDataPath', so you might need to adjust your paths and uriType before     testing this version.   
> >   
Still crashing:

**Comment by Manurocker95** [comment]
there is no attachment

**Comment by Manurocker95** [comment]
> I added the missing String null check shown in your error log. Try replacing the aar with the one in the attachment. It means the path is empty.

there is no attachment

**Comment by Manurocker95** [comment]
It doesn't crash anymore but now I'm getting this error from event: 

Unity has received an error from Native: Failed to initiate MediaPlayer: MediaItem doesn't exist.
Glitch9.NativePlugins.NativeMediaPlayer.NativeMediaPlayer:UnityReceiveError(String)

and Glitch9.NativePlugins.NativeMediaPlayer.MediaPlayer.set_ShuffleModeEnabled (System.Boolean value) [0x00000] in <00000000000000000000000000000000>:0

the second one might be because even if I call initialize and then set the shuffle, I should do it on prepare.

**Comment by Manurocker95** [comment]
The project name has special characters and white space, could it be related to that?

**Comment by Glitch9Inc** [comment]
Ah if you are using codes to create media items,
change  
mediaitem.uri = something
to
mediaitem.persistentDataPath = something
 

------------------------------------------------------------------------------

For bug reports or issues, please visit  Glitch9-Support Issues (https://github.com/Glitch9Inc/Glitch9-Support/issues).

Work Hours:
Korea Standard Time (KST):

Monday to Friday: 9:30 AM - 8:00 PM

Saturday: Closed

Sunday: 12:00 PM - 6:00 PM

Pacific Standard Time (PST):

Monday to Friday: 4:30 PM (previous day) - 3:00 AM

Saturday: Closed

Sunday: 7:00 PM (previous day) - 1:00 AM

**Comment by Manurocker95** [comment]
I'm using:

var lastItem = new MediaItem(UriType.PersistentDataPath, filePath);

**Comment by Manurocker95** [comment]
![image](https://github.com/Glitch9Inc/Glitch9-Support/assets/17181899/167aff40-414c-45eb-8d6e-fcf2a40ff0ac)

It seems not loading the correct playlist on manual initialization (it did before and there were no code changes)

**Comment by Manurocker95** [comment]
Add media item overrides datapath

**Comment by Manurocker95** [comment]
Unity has received an error from Native: Error: 1, -2147483648

any idea what this could mean?

**Comment by Glitch9Inc** [comment]
It means 'unknown error' generated by android media player. From my experience 90 percent of the time it was related to the format of the audio file. Refer to  

https://developer.android.com/media/platform/supported-formats for the supported formats.

------------------------------------------------------------------------------

For bug reports or issues, please visit  Glitch9-Support Issues (https://github.com/Glitch9Inc/Glitch9-Support/issues).

Work Hours:
Korea Standard Time (KST):

Monday to Friday: 9:30 AM - 8:00 PM

Saturday: Closed

Sunday: 12:00 PM - 6:00 PM

Pacific Standard Time (PST):

Monday to Friday: 4:30 PM (previous day) - 3:00 AM

Saturday: Closed

Sunday: 7:00 PM (previous day) - 1:00 AM


On 07/05/2024, 6:59:56 PM, "Manuel Rodríguez Matesanz"  ***@***.***>  wrote:

> Unity has received an error from Native: Error: 1, -2147483648
>
>   
any idea what this could mean?
>
>   
El vie, 5 jul 2024 a las 11:41, Manuel Rodríguez Matesanz (<
>

**Comment by Manurocker95** [comment]
These exact audios worked all the time until the rework. They are all in
MP3 format...

**Comment by Manurocker95** [comment]
It seems related to the datapath because it works on editor but on android
it seems to expect a different thing

[image: image.png]

**Comment by Manurocker95** [comment]
I would need to know what are the exact expected values for the
persistentDatapath, downloadPath etc because they don't match...

**Comment by Manurocker95** [comment]
Okay, you are adding "files/" to the path for no reason. That's why it
doesn't work.

**Comment by Manurocker95** [comment]
2024/07/05 13:08:35.847 22467 22467 Warn System.err [NativeMediaPlayer]
File does not exist at
/storage/emulated/0/Android/data/com.Manurocker95.Jukebox/files/Audio/Albums/MyAlbum/MySong.mp3.
Downloading... Does not exist but
 /storage/emulated/0/Android/data/com.Manurocker95.Jukebox/Audio/Albums/MyAlbum/MySong.mp3
DOES exist and that's the persistentDatapath I'm setting to the mediaItem

**Comment by Manurocker95** [comment]
nvm, that's Android's persistent datapath and the file is found under
storage/emulated/0/Android/data/com.Manurocker95.Jukebox/files/Audio/Albums/MyAlbum/MySong.mp3
if I do File.Exists but NPM seems to not find it

**Comment by Manurocker95** [comment]
ManualInitialization.cs example does not work. Can you update it to match the new way to load from persistentdatapath?

**Comment by Manurocker95** [comment]
This bug is still happening on latest update.  The first load still freezes the device for a few seconds but afterwards, when it loads, the changes between them are instant. Could it be possible to send just the list to the backend plugin and load the playslists as one single item playlist so the loading times get reduced?

As the main thread gets stuck, the metadata retreive part or the sending to the plugin part takes the most loading times

**Comment by Manurocker95** [comment]
okay, it seems to work now. Related to the freeze itself, here you have an
example on the Retroid Pocket 4 Pro with (8GB of RAM):

https://streamable.com/qb3cwm

As you can see single items load instantly but big playlists take a huge
amount of time freezing the main thread until everything gets loaded in
background.

**Comment by Glitch9Inc** [comment]
The only thing I can do more to enhance the performance of the passing logic involves modifying all initiation logics for 4 different native music player. Will work more on it later. Closing.
